driver:
  name: vagrant
  customize:
    memory: 1024
    # network:
    #   - ["private_network", {ip: 33.33.33.10}]

provisioner:
  name: chef_solo
  require_chef_omnibus: true
  chef_omnibus_url: https://www.chef.io/chef/install.sh
  cookbook_path: "cookbooks"


platforms:
  - name: RE-ubuntu-12.04
    driver:
      box: ubuntu_12.04
      box_url: /Users/loadx/DMGs/VBoxes/ubuntu-12.04-new.box

suites:
  - name: web
    run_list:
      - recipe[REA]
